#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export cleanroom builds into various different formats.

@author: Tobias Hunger <tobias.hunger@gmail.com>
"""


from cleanroom.buildcontainer.main import run


if __name__ == "__main__":
    run()
