#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Main CleanRoom binary.

@author: Tobias Hunger <tobias.hunger@gmail.com>
"""


import cleanroom.generator.main as main


if __name__ == '__main__':
    main.run()
