#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Cleanroom Imager binary

@author: Tobias Hunger <tobias.hunger@gmail.com>
"""


import cleanroom.imager.main as main


if __name__ == '__main__':
    main.run()
