#!/usr/bin/bash

function fail {
    echo "$1"
    exit $2
}

grep '^root:[x!]?:' etc/shadow && fail "No root password set in /etc/shadow, fail", 1
grep ':\\\$' etc/shadow && fail "Broken password set in /etc/shadow, fail", 2

echo "Root password set in /etc/shadow, ok"
