#!/usr/bin/bash

function fail {
    echo "$1"
    exit $2
}

grep "^KillUserProcesses=yes" etc/systemd/logind.conf \
    || fail "KillUserProcesses not enabled in logind.conf, fail" 1

echo "KillUserProcesses enabled in logind.conf, ok"

